services:
  database:
    image: postgres:18
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
