-- Drop tables with foreign key dependencies first
DROP TABLE IF EXISTS GROUPS_USERS;
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS USER_PERSONNE;

-- Drop tables with no dependencies
DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS PLATFORMS;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PERSONNE;

-- drop triggers
DROP TRIGGER IF EXISTS GROUP_EXISTS ON GROUPS;
DROP TRIGGER IF EXISTS PLATFORM_EXISTS ON PLATFORMS;
DROP TRIGGER IF EXISTS USER_EXISTS ON USERS;
DROP TRIGGER IF EXISTS PERSONNE_EXISTS ON PERSONNE;

-- drop funcions
DROP FUNCTION IF EXISTS check_group_exists();
DROP FUNCTION IF EXISTS check_platform_exists();
DROP FUNCTION IF EXISTS check_user_exists();
DROP FUNCTION IF EXISTS check_personne_exists();
