services:
  database:
    image: postgres:18.3-trixie
    restart: always
    volumes:
      - /home/randr/Projects/TheSharePlace/backEnd/database:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
